[package]
name = "iroh-willow"
version = "0.28.0"
edition = "2021"
readme = "README.md"
description = "willow protocol implementation for iroh"
license = "MIT/Apache-2.0"
authors = ["n0 team"]
repository = "https://github.com/n0-computer/iroh"

# Sadly this also needs to be updated in .github/workflows/ci.yml
rust-version = "1.77"

[lints]
workspace = true

[dependencies]
anyhow = "1"
bytes = { version = "1.4", features = ["serde"] }
curve25519-dalek = { version = "4.1.3", features = [ "digest", "rand_core", "serde", ] }
derive_more = { version = "1.0.0", features = [ "debug", "deref", "display", "from", "try_into", "into", "as_ref", "try_from", ] }
ed25519-dalek = { version = "2.0.0", features = ["serde", "rand_core"] }
either = "1.13.0"
futures-buffered = "0.2.6"
futures-concurrency = "7.6.0"
futures-lite = "2.3.0"
futures-util = "0.3.30"
genawaiter = "0.99.1"
hex = "0.4.3"
iroh-base = { version = "0.30.0" }
iroh-blake3 = "1.4.5"
# iroh-blobs = { version = "0.30.0" }
iroh-blobs = { git = "https://github.com/n0-computer/iroh-blobs", branch = "matheus23/verified-streams" }
iroh-io = { version = "0.6.0", features = ["stats"] }
iroh-metrics = { version = "0.30.0", optional = true }
iroh = { version = "0.30.0" }
meadowcap = "0.1.0"
nested_enum_utils = "0.1.0"
postcard = { version = "1", default-features = false, features = [ "alloc", "use-std", "experimental-derive", ] }
quic-rpc = "0.15.1"
quic-rpc-derive = "0.15.0"
rand = "0.8.5"
rand_core = "0.6.4"
redb = { version = "2.0.0" }
ref-cast = "1.0.23"
self_cell = "1.0.4"
serde = { version = "1.0.164", features = ["derive"] }
serde-error = "0.1.3"
sha2 = "0.10.8"
strum = { version = "0.26", features = ["derive"] }
syncify = "0.1.0"
thiserror = "1"
tokio = { version = "1", features = ["sync"] }
tokio-stream = { version = "0.1.15", features = ["sync"] }
tokio-util = { version = "0.7", features = ["io-util", "io"] }
tracing = "0.1"
ufotofu = { version = "0.4.1", features = ["std"] }
willow-data-model = "0.1.0"
willow-encoding = "0.1.0"
willow-store = { git = "https://github.com/n0-computer/willow-store.git", branch = "main" }
zerocopy = { version = "0.7", features = ["derive"] }
zerocopy-derive = "0.7"
data-encoding = "2.6.0"

[dev-dependencies]
iroh-test = { version = "0.30" }
iroh = { version = "0.30", features = ["test-utils"] }
rand_chacha = "0.3.1"
tokio = { version = "1", features = ["sync", "macros"] }
proptest = "1.2.0"
tempfile = "3.4"
testresult = "0.4.0"
test-strategy = "0.3.1"
tracing-subscriber = "0.3.18"

[features]
default = ["metrics"]
metrics = ["iroh-metrics"]

[profile.release]
debug = true

[profile.bench]
debug = true

[profile.dev-ci]
inherits = 'dev'
opt-level = 1

[profile.optimized-release]
inherits = 'release'
debug = false
lto = true
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false

[profile.dev.package]
# optimize crypto dependencies in dev mode
ed25519-dalek = { opt-level = 3 }
curve25519-dalek = { opt-level = 3 }
iroh-blake3 = { opt-level = 3 }

[workspace.lints.rust]
missing_debug_implementations = "warn"

# We use this --cfg for documenting the cargo features on which an API
# is available.  To preview this locally use: RUSTFLAGS="--cfg
# iroh_docsrs cargo +nightly doc --all-features".  We use our own
# iroh_docsrs instead of the common docsrs to avoid also enabling this
# feature in any dependencies, because some indirect dependencies
# require a feature enabled when using `--cfg docsrs` which we can not
# do.  To enable for a crate set `#![cfg_attr(iroh_docsrs,
# feature(doc_cfg))]` in the crate.
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(iroh_docsrs)"] }

[workspace.lints.clippy]
unused-async = "warn"

[patch.crates-io]
# willow-data-model = { path = "../willow-rs/data-model" }
# willow-encoding = { path = "../willow-rs/encoding" }
# meadowcap = { path = "../willow-rs/meadowcap" }
willow-data-model = { git = "https://github.com/n0-computer/willow-rs.git", branch = "main" }
willow-encoding = { git = "https://github.com/n0-computer/willow-rs.git", branch = "main" }
meadowcap = { git = "https://github.com/n0-computer/willow-rs.git", branch = "main" }

# iroh-base = { git = "https://github.com/n0-computer/iroh", branch = "main" }
# iroh-net = { git = "https://github.com/n0-computer/iroh", branch = "main" }
# iroh-metrics = { git = "https://github.com/n0-computer/iroh", branch = "main" }
# iroh-test = { git = "https://github.com/n0-computer/iroh", branch = "main" }
# iroh-router = { git = "https://github.com/n0-computer/iroh", branch = "main" }

# iroh-blobs = { git = "https://github.com/n0-computer/iroh-blobs", branch = "matheus23/verified-streams" }
